#------------------------------------------------------------------------------
# Add a Python requirement to a tutor openedx container configuration.
#   - download the repository
#   - create a private.txt file if it does not already exist in the Ubuntu environment
#   - add the requirement to the private.txt
#
#------------------------------------------------------------------------------
name: Open edX Tutor k8s build openedx - add requirement
description: 'Use Tutor to add a Python requirement to your Docker container'
branding:
  icon: 'cloud'
  color: 'orange'
inputs:
  repository:
    description: 'Repository anme of the additional XBlock repository to install for this build'
    required: true
  repository-organization:
    description: 'the Github organization containing the XBlock repository to install for this build'
    required: true
  repository-ref:
    description: 'branch or release of the XBlock repository'
    required: true
outputs:
  path:
    description: 'The local file path to the requirement home folder. Example: '
    value: ${{ steps.finalize.outputs.path }}
runs:
  using: "composite"
  steps:
    - name: Find tutor
      id: find-tutor
      shell: bash
      run: |
        if [ ! -d "$(tutor config printroot)/" ]; then
          echo "This action requires tutor. Add Github Action openedx-actions/tutor-k8s-init to your workflow prior to running this action. Exiting"
          echo "::set-output found='false'"
          exit
        else
          echo "::set-output found='true'"
        fi

    - name: Setup environment
      if: ${{ steps.find-tutor.outputs.found == 'true' }}
      id: init
      shell: bash
      run: |-
        echo "PLUGINS_PATH=$(tutor config printroot)/env/build/openedx/requirements" >> $GITHUB_ENV

    - uses: actions/checkout@v3.0.2

    - name: Checkout repo
      if: ${{ steps.find-tutor.outputs.found == 'true' }}
      id: checkout-repo
      uses: actions/checkout@v3.0.2
      with:
        repository: ${{ inputs.repository-organization }}/${{ inputs.repository }}
        path: tutor/env/build/openedx/requirements/${{ inputs.repository }}
        token: ${{ github.token }}
        ref: ${{ inputs.repository-ref }}

    - name: Create private.txt
      if: ${{ steps.find-tutor.outputs.found == 'true' }}
      id: create-private-txt
      shell: bash
      run: ${{ github.action_path }}/scripts/create-private-txt.sh

    - name: Add requirement to private.txt
      if: ${{ steps.find-tutor.outputs.found == 'true' }}
      id: add-requirement
      shell: bash
      run: |-
        echo "-e ./${{ inputs.repository }}" > ${PLUGINS_PATH}/private.txt
        echo "new requirement added to private.txt: "
        cat "${PLUGINS_PATH}/private.txt"

    - name: Finalize workflow
      id: finalize
      shell: bash
      run: |
        echo "::set-output path=${{ github.action_path }}/tutor/env/build/openedx/requirements/${{ inputs.repository }}"
